services:
  db:
    image: postgres:15-alpine
    container_name: foodgram-db
    restart: always
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  backend:
    container_name: foodgram-backend
    build: ../backend/foodgram
    restart: always
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_volume:/app/staticfiles/
      - media_volume:/app/media/
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000
      "
    expose:
      - "8000"
  frontend:
    container_name: foodgram-frontend
    build: ../frontend
    volumes:
      - ../frontend/build:/usr/share/nginx/html:ro
    restart: "no"

  nginx:
    image: nginx:1.25.4-alpine
    container_name: foodgram-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/static/
      - media_volume:/media/
      - ../frontend/build:/usr/share/nginx/html:ro
    depends_on:
      - backend


volumes:
  pg_data:
  static_volume:
  media_volume:
  frontend_build:

