services:
  db:
    image: postgres:15-alpine
    container_name: foodgram-db
    restart: always
    env_file: .env
    volumes:
       - pg_data:/var/lib/postgresql/data/
    ports:
       - "5432:5432"

  backend:
    container_name: foodgram-backend
    build: ../backend/foodgram
    restart: always
    env_file: .env
    depends_on: 
      - db
    volumes:
      - static_volume:/app/staticfiles/
      - media_volume:/app/media/
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000
      "
    expose:
      - "8000"

  frontend:
    container_name: foodgram-frontend-build
    build: ../frontend
    volumes:
      - frontend_build:/app/build
    command: ["true"] # контейнер только для сборки

  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - frontend_build:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - media_volume:/var/html/media:ro
      - static_volume:/var/html/staticfiles:ro

volumes:
  pg_data:
  static_volume:
  media_volume:
  frontend_build:

